---
name: Molecule Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        MOLECULE_DISTRO: ['centos:centos7', 'centos:centos8', 'fedora:32', 'fedora:33', 'ubuntu:eoan', 'ubuntu:focal']
        python-version: ['3.5']

    steps:
      - name: Check out code.
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule docker

      - name: Test with molecule
        run: |
          molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.MOLECULE_DISTRO }}
