version: '3'
services:
  ubuntu1:
    image: ubuntu-ssh:v1
    container_name: ubuntu_container_1
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    tty: true
  ubuntu2:
    image: ubuntu-ssh:v1
    container_name: ubuntu_container_2
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    tty: true
