---
- hosts: dev
  gather_facts: True # 預設是 True，會主動蒐集資訊
  roles: # 使用 ansible role 在 dev 機器上安裝 git
    - { role: 0ta2.git_role, become: yes } # role 提權: https://reurl.cc/dmm44D
  tasks:
    # task 1
    - name: test connection
      ping:
      register: message # "register "允許捕獲模塊的執行結果，並在 playbook 中的其他地方使用這些結果

    # task 2
    - name: print debug message
      debug:
        msg: "{{ message }}"